version: 1.0.{build}

branches:
	only:
		- master

assembly_info:
	patch: true
	file: AssemblyInfo.*
	assembly_version: "{version}"
	assembly_file_version: "{version}"
	assembly_informational_version: "{version}"

configuration: Release

build:
	project: ZimCode.IO.sln

after_test:
	- ps: .\NuGet\pack.ps1

artifacts:
	- path: IO\bin\Release\ZimCode.IO.dll
		name: ZimCode.IO.dll
	- path: '**\*.nupkg'

deploy:
	provider: NuGet
	api_key:
		secure: q0jNyZQd8uln/uBv7zAyUcieNxbL/YVAMo1ShrsDlg/xZa+av+en4DpIGXe5stGo
	artifact: /.*\.nupkg/